package parts

func (eplangruppe *EPLANGRUPPEN) setInfo() {
	eplangruppe.Gewerk = map[int]string{
		0: "Undefiniert",
		1: "Elektrotechnik",
		2: "Fluid",
		3: "Mechanik",
		4: "Verfahrenstechnik",
	}
	eplangruppe.Produktgruppe = map[int]string{
		0:   "Undefiniert",
		2:   "Relais, Schütze",
		7:   "Schutzeinrichtungen",
		8:   "Röhren, Halbleiter",
		9:   "Motoren",
		30:  "Aggregate und Anlagen",
		31:  "Aktoren, allgemein",
		32:  "Fluidmotor",
		33:  "Filter (Fluid)",
		34:  "Fluid Control Terminal",
		35:  "Kupplungen (Fluid)",
		36:  "Messanschlüsse",
		37:  "Verbindungen (Fluid)",
		38:  "Messgeräte",
		39:  "Klemmen",
		40:  "Pumpen (Fluid)",
		41:  "Signalaufnehmer",
		42:  "Fluid Sonderbauteile",
		43:  "Speicher",
		44:  "Ventile (Fluid)",
		45:  "Wärmetauscher (Fluid)",
		46:  "Anschlussplatten",
		47:  "Zubehör (Fluid)",
		48:  "Gehäuse",
		49:  "Stecker",
		50:  "Gehäusezubehör Außenanbau",
		51:  "Gehäusezubehör Innenanbau",
		52:  "Verschlussysteme",
		53:  "Kabelkanäle",
		54:  "Sammelschienen",
		55:  "Schaltschränke",
		56:  "Abzugshaube",
		57:  "Elektrolysezelle",
		58:  "Lagerung",
		59:  "Schornstein",
		60:  "Umformer",
		61:  "Antriebsmachine",
		62:  "Absperramatur",
		63:  "Dreiwegearmatur",
		64:  "Rückschlagarmatur",
		65:  "Behälter",
		66:  "Behältereinheit",
		67:  "Abscheider (Verfahrenstechnik)",
		68:  "Filter (Verfahrenstechnik)",
		69:  "Sieb",
		70:  "Förderer",
		71:  "Hebe",
		72:  "Transporter",
		73:  "Behälter-Mantel",
		74:  "Behälter-Rohrschlange",
		75:  "Dampfkessel",
		76:  "Kühler",
		77:  "Ofen",
		78:  "Trockner",
		79:  "Verdampfer",
		80:  "Wärmetauscher (Verfahrenstechnik)",
		81:  "Knetter",
		82:  "Mischer",
		83:  "Rührer",
		84:  "Kompressor / Verdichter",
		85:  "Pumpen (Verfahrenstechnik)",
		86:  "Vakuumpumpe",
		87:  "Ventilator",
		88:  "Rohrleitungsteil",
		89:  "Meldeeirichtungen",
		91:  "Zentrifuge",
		92:  "Messeinrichtung",
		93:  "Waage",
		94:  "Formgeber",
		95:  "Sichter",
		96:  "Sortierer",
		97:  "Zerkleinerer",
		98:  "Zuteiler",
		99:  "Feldverteiler",
		100: "Verbindungen",
		101: "Montageplatten",
		102: "Heizung",
		103: "Leuchte",
		104: "Heizung (Fluid)",
		105: "Zylinder",
		106: "Bremse (Fluid)",
		107: "Gleichrichter",
		108: "Bremse",
		109: "Kupplungen",
		10:  "Messgeräte, Prüfeinrichtungen",
		110: "Ventile",
		111: "Druckbegrenzer",
		112: "Abscheider (Fluid)",
		113: "Leitungsverteiler - verbinder (Verfahrenstechnik)",
		114: "Zubehör (Verfahrenstechnik)",
		115: "Medizintechnik (Fluid)",
		116: "Benutzerdefinierte Schiene",
		117: "19 Zoll-Ausbautechnik",
		118: "Strecke (Topologie)",
		119: "Verlegepunkt (Topologie)",
		11:  "Widerstände",
		121: "Verbindungen (Verfahrenstechnik)",
		125: "Verlegezubehör",
		126: "Montageanordnung",
		127: "Leitungen / Pakete (Verfahrenstechnik)",
		128: "Leitungen / Pakete (Fluid)",
		129: "Leitungsverteiler - verbinder",
		12:  "Sensorik, Schalter und Taster",
		13:  "Transformatoren",

		1:  "Allgemein",
		17: "Verschiedenes",
		20: "Spannungsquelle und Generator",
		21: "Induktivitäten",
		22: "Verstärker, Regler",
		23: "Starkstrom-Schaltgerät",
		24: "Abschlüsse, Filter",
		25: "Übertragungswege",
		26: "SPS (Elektrotechnik, Fluid)",

		29: "Kabel",
		3:  "Klemmen",
		4:  "Stecker",
		5:  "Umformer",
		6:  "Sieb",
	}

	eplangruppe.Produktuntergruppe = map[int]string{
		3: "Hilfsblock",

		1:   "Allgemein",
		0:   "Undefiniert",
		100: "Druckspeicher",
		101: "Kolbenspeicher",
		102: "Sicherheitsspeicher",
		103: "Speicherblöcke",
		104: "Druckbegrenzer",
		105: "Druckventile",
		106: "Entlüftungsventile",
		107: "Kolbenventile",
		108: "Kugelhanh pneumatisch",
		109: "Manometerschutzventile",
		10:  "Querverbinder (Klemmen, Stecker)",
		110: "Manometerwahlschalter",
		111: "Progressivverteiler",
		112: "Rückschlagventile",
		113: "Sperrventile",
		114: "Stromventile",
		115: "Stromverteilerventile",
		116: "Thermostatventile",
		117: "Wegekonzülventile",
		118: "Wegeventile",
		11:  "Schienen (Klemmen, Stecker)",
		121: "Kupplungen (Fluid)",
		122: "Pumpenträger",
		123: "Schalldämpfer (Fluid)",
		124: "Tanks (Fluid)",
		126: "Verschraubungen",
		127: "Wasserabscheider",
		128: "Zeichnungsbehälter",
		12:  "Abdeckung (Klemmen, Stecker)",
		130: "Tür",
		131: "Rack / Seitenwand",
		132: "Dach",
		133: "Boden",
		134: "Sockel",
		135: "Montageplatten",
		136: "Zubehör (Gehäuse, Montageanordnung, Strecke (Topologie), Verlegepunkt (Topologie))",
		139: "Kabeltragstangen",
		13:  "Abschluss (Klemmen, Stecker)",

		140: "Tragschiene (Mechanik)",
		141: "Gleitschienen",
		142: "C-Profilschienen",
		146: "System",
		147: "Halter",
		148: "Adapter",
		14:  "Trennwand (Klemmen, Stecker)",
		150: "Einzelteil",
		151: "Korpus",
		152: "SPS-Eingangskarte analog",
		153: "SPS-Eingangskarte digital",
		154: "SPS-Ausgangskarte analog",
		155: "SPS-Ausgangskarte digital",
		156: "Tanks (Verfahrenstechnik)",
		157: "Bunker",
		158: "Silo",
		159: "Kolonnen",
		15:  "Steckergehäuse (Klemmen, Stecker)",
		160: "Reaktor",
		161: "Absperrarmatur",
		162: "Absperrventil",
		163: "Absperrklappe",
		164: "Rückschlagarmatur",
		165: "Rückschlagventil",
		166: "Rückschlagklappe",
		167: "Dreiwegearmatur",
		169: "Dreiwegeklappe",
		16:  "Steckerzubehör (Klemmen, Stecker)",
		170: "Drosselscheibe",
		171: "Blindscheibe",
		172: "Trichter",
		173: "Auslass",
		174: "Schalldämpfer (Verfahrenstechnik)",
		175: "Schauglas",
		176: "Mischdüse",
		177: "Schutzzünder",
		178: "Kondensatableiter",
		179: "Flanschpaar",
		17:  "Werkzeug (Klemmen, Stecker)",
		180: "Reduzierung",
		181: "Kupplungen (Verfahrenstechnik)",
		182: "Syphon",
		183: "Presse",
		184: "Vorkonfektioniert",
		185: "Anzeigegerät",
		186: "Meldeleuchte",
		187: "Messwertschreiber",
		188: "Meldeeirichtung, akustisch",
		189: "Fehlerspannungs-Schutzschalter",
		18:  "Testzubehör (Klemmen, Stecker)",
		190: "Fehlerstrom-Schutzschalter",
		191: "Motorschutzschalter",
		192: "Schmelzsicherung",
		193: "Schutzschalter",
		194: "Sicherungsausautomat",
		195: "Meldeeinrichtung, akustisch (Fluid)",
		196: "Meldeeinrichtung, optisch",
		197: "Messwertschreiber (Fluid)",
		198: "Logikbauteil",
		19:  "Artikel (Quelle)",
		200: "Ventil / Verteiler",
		201: "Schutzkreis",
		202: "Analoges Sensor",
		203: "Digitales Sensor, allgemein",
		204: "Endschalter",
		205: "Grenzwertgeber",
		206: "Lichtschranke",
		207: "Näheungsschalter",
		208: "Schalter / Taster",
		209: "Generator",
		20:  "Artikel (Ziel)",
		210: "Spannungsquelle",
		211: "Sammelschienen-Abdeckung",
		212: "Schwenkrahmen",
		213: "Montage-Chassis",
		214: "Montageschiene",
		215: "Stifteinsatz",
		216: "Buchseneinsatz",
		217: "Rohre (Fluid)",
		218: "Schaltplatine (Klemmen, Stecker)",
		219: "Schaltbrücke (Klemmen, Stecker)",
		220: "Steckaufsatz (Klemmen, Stecker)",
		221: "Schiene",
		223: "Schlauche (Verfahrenstechnik)",
		224: "Rohe (Verfahrenstechnik)",
		225: "Kabel / Schlauchbefestigung",
		226: "Kabel / Schlauchschutz",
		227: "Kabel / Schlauchschutz",
		228: "Flachbandkabel",
		229: "Crimpkontakt",
		230: "Kontaktleinsatz",
		2:   "Schütze",
		47:  "Hochdruckanlagen",
		48:  "Hochdrucktanks",
		49:  "Hydrauliktanks",
		4:   "Klemme (Klemmen, Stecker)",

		51: "Kühlaggregate",
		52: "Schaltschrankkühlgeräte",
		53: "Schraubenpsindelkompressoren",
		54: "Scrollkompressoren",
		55: "Wärmetauscher",
		56: "Zentralschmieraggregate",
		57: "Anschlussplatten",
		58: "Adeckplatten",
		59: "Adapterplatten",
		5:  "Tragschiene (Klemmen, Stecker)",
		60: "Blockgehäuse",
		61: "Flansche",
		62: "Blockgehäuse",
		63: "Reduzierplatten",
		64: "Reihenanschlussplatten",
		65: "Steuerblöcke",
		66: "Zwischenplatten",
		67: "Hydromotoren",
		68: "Schwenkantrieb",
		69: "Zylinder",
		6:  "Endwinkel (Klemmen, Stecker)",
		71: "Belüftungsfilter",
		72: "Doppelumschaltfilter",
		73: "Druckluftfilter",
		74: "Einfachfilter",
		75: "Leitungstief",
		76: "Rückluftfilter",
		77: "Rückluftfilter vollautomatisch",
		79: "Kupplungs-Motorpumpen",
		7:  "Klemmenschild (Klemmen, Stecker)",
		80: "Messkupplungen",
		81: "Verschlusskupplungen",
		82: "Schläuche (Fluid)",
		83: "Verschiedenes",
		85: "Manometer",
		86: "Thermometer",
		87: "Kompressoren",
		88: "Konstantpumpen",
		89: "Kreiselpumpen",
		8:  "Weiche Schilder (Klemmen, Stecker)",
		90: "Schraubenspindelpumpen",
		91: "Verstellpumpen",
		92: "Druckschalter",
		93: "Füllstandsschalter",
		94: "Signalaufnehmer-Manometer",
		95: "Näherungsschalter (Fluid)",
		96: "Strömungswächter",
		97: "Temperatursensoren",

		50: "Kühlaggregate",

		70: "Endwinkel (Klemmen, Stecker)",

		78: "Klemmenschild (Klemmen, Stecker)",

		84: "Verschiedenes",
		99: "Absperrspeicher",
		9:  "Leistenschild (Klemmen, Stecker)",
	}
}
