package parts

func (eplangruppe EPLANGRUPPEN) setInfo() {
	eplangruppe.gewerk = map[int]string{
		0: "Undefiniert",
		1: "Elektrotechnik",
		2: "Fluid",
		3: "Mechanik",
		4: "Verfahrenstechnik",
	}
	eplangruppe.produktgruppe = map[int]string{
		0:   "Undefiniert",
		2:   "Relais, Schütze",
		7:   "Schutzeinrichtungen",
		8:   "Röhren, Halbleiter",
		9:   "Motoren",
		30:  "Aggregate und Anlagen",
		31:  "Aktoren, allgemein",
		32:  "Fluidmotor",
		33:  "Filter (Fluid)",
		34:  "Fluid Control Terminal",
		35:  "Kupplungen (Fluid)",
		36:  "Messanschlüsse",
		37:  "Verbindungen (Fluid)",
		38:  "Messgeräte",
		39:  "Klemmen",
		40:  "Pumpen (Fluid)",
		41:  "Signalaufnehmer",
		42:  "Fluid Sonderbauteile",
		43:  "Speicher",
		44:  "Ventile (Fluid)",
		45:  "Wärmetauscher (Fluid)",
		46:  "Anschlussplatten",
		47:  "Zubehör (Fluid)",
		48:  "Gehäuse",
		49:  "Stecker",
		50:  "Gehäusezubehör Außenanbau",
		51:  "Gehäusezubehör Innenanbau",
		52:  "Verschlussysteme",
		53:  "Kabelkanäle",
		54:  "Sammelschienen",
		55:  "Schaltschränke",
		56:  "Abzugshaube",
		57:  "Elektrolysezelle",
		58:  "Lagerung",
		59:  "Schornstein",
		60:  "Umformer",
		61:  "Antriebsmachine",
		62:  "Absperramatur",
		63:  "Dreiwegearmatur",
		64:  "Rückschlagarmatur",
		65:  "Behälter",
		66:  "Behältereinheit",
		67:  "Abscheider (Verfahrenstechnik)",
		68:  "Filter (Verfahrenstechnik)",
		69:  "Sieb",
		70:  "Förderer",
		71:  "Hebe",
		72:  "Transporter",
		73:  "Behälter-Mantel",
		74:  "Behälter-Rohrschlange",
		75:  "Dampfkessel",
		76:  "Kühler",
		77:  "Ofen",
		78:  "Trockner",
		79:  "Verdampfer",
		80:  "Wärmetauscher (Verfahrenstechnik)",
		81:  "Knetter",
		82:  "Mischer",
		83:  "Rührer",
		84:  "Kompressor / Verdichter",
		85:  "Pumpen (Verfahrenstechnik)",
		86:  "Vakuumpumpe",
		87:  "Ventilator",
		88:  "Rohrleitungsteil",
		89:  "Meldeeirichtungen",
		91:  "Zentrifuge",
		92:  "Messeinrichtung",
		93:  "Waage",
		94:  "Formgeber",
		95:  "Sichter",
		96:  "Sortierer",
		97:  "Zerkleinerer",
		98:  "Zuteiler",
		99:  "Feldverteiler",
		100: "Verbindungen",
		101: "Montageplatten",
		102: "Heizung",
		103: "Leuchte",
		104: "Heizung (Fluid)",
		105: "Zylinder",
		106: "Bremse (Fluid)",
		107: "Gleichrichter",
		108: "Bremse",
		109: "Kupplungen",
		110: "Messgeräte, Prüfeinrichtungen",
		111: "Ventile",
		112: "Druckbegrenzer",
		113: "Abscheider (Fluid)",
		114: "Leitungsverteiler - verbinder (Verfahrenstechnik)",
		115: "Zubehör (Verfahrenstechnik)",
		116: "Medizintechnik (Fluid)",
		117: "Benutzerdefinierte Schiene",
		118: "19 Zoll-Ausbautechnik",
		119: "Strecke (Topologie)",
		120: "Verlegepunkt (Topologie)",
		121: "Widerstände",
		122: "Verbindungen (Verfahrenstechnik)",
		123: "Verlegezubehör",
		124: "Montageanordnung",
		125: "Leitungen / Pakete (Verfahrenstechnik)",
		126: "Leitungen / Pakete (Fluid)",
		127: "Leitungsverteiler - verbinder",
		128: "Sensorik, Schalter und Taster",
		129: "Transformatoren",
		130: "Modulatoren",
		131: "Elektrisch betätigte mechanische Einrichtungen",
		132: "Elektrotechn Sonderbauteile",
		133: "Verschiedenes",
		134: "Kondensatoren",
		135: "Logikbauteile",
		136: "Allgemeine",
		137: "Spannungsquelle und Generator",
		138: "Induktivitäten",
		139: "Verstärker, Regler",
		140: "Abschluss, Filter",
		141: "Übertragungsweg",
		142: "SPS (Elektrotechnik, Fluid)",
		143: "Kabel",
	}

	eplangruppe.produktuntergruppe = map[int]string{
		0:   "Undefiniert",
		100: "Druckspeicher",
		101: "Kolbenspeicher",
		102: "Sicherheitsspeicher",
		103: "Speicherblöcke",
		104: "Druckbegrenzer",
		105: "Druckventile",
		106: "Entlüftungsventile",
		107: "Kolbenventile",
		108: "Kugelhanh pneumatisch",
		109: "Manometerschutzventile",
		110: "Querverbinder (Klemmen, Stecker)",
		111: "Manometerwahlschalter",
		112: "Progressivverteiler",
		113: "Rückschlagventile",
		114: "Sperrventile",
		115: "Stromventile",
		116: "Stromverteilerventile",
		117: "Thermostatventile",
		118: "Wegekonzülventile",
		119: "Wegeventile",
		120: "Schienen (Klemmen, Stecker)",
		121: "Kupplungen (Fluid)",
		122: "Pumpenträger",
		123: "Schalldämpfer (Fluid)",
		124: "Tanks (Fluid)",
		125: "Verschraubungen",
		126: "Wasserabscheider",
		127: "Zeichnungsbehälter",
		128: "Abdeckung (Klemmen, Stecker)",
		130: "Tür",
		131: "Rack / Seitenwand",
		132: "Dach",
		133: "Boden",
		134: "Sockel",
		135: "Montageplatten",
		136: "Zubehör (Gehäuse, Montageanordnung, Strecke (Topologie), Verlegepunkt (Topologie))",
		137: "Kabeltragstangen",
		138: "Abschluss (Klemmen, Stecker)",
		139: "Flächengreifer (Mechanik)",
		140: "Gleitschien",
		141: "C-Profilschienen",
		146: "System",
		147: "Halter",
		148: "Adapter",
		149: "Trennwand (Klemmen, Stecker)",
		150: "Einzelteil",
		151: "Korpus",
		152: "SPS-Eingangskarte analog",
		153: "SPS-Eingangskarte digital",
		154: "SPS-Ausgangskarte analog",
		155: "SPS-Ausgangskarte digital",
		156: "Tanks (Verfahrenstechnik)",
		158: "Bunker",
		159: "Silo",
		160: "Kolonnen",
		161: "Steckergehäuse (Klemmen, Stecker)",
		162: "Reaktor",
		163: "Absperrarmatur",
		164: "Absperrschieber",
		165: "Absperrklappe",
		166: "Rückschlagarmatur",
		167: "Rückschlagventil",
		168: "Rückschlagklappe",
		169: "Dreiwegearmatur",
		170: "Dreiwegeklappe",
		171: "Steckerzubehör (Klemmen, Stecker)",
		172: "Brosselscheibe",
		173: "Trichter",
		174: "Aulass",
		175: "Schalldämpfer (Verfahrenstechnik)",
		176: "Schauglas",
		177: "Mischdüse",
		178: "Schutzzünder",
		179: "Kondensatableiter",
		180: "Flanschpaar",
		181: "Werkzeug (Klemmen, Stecker)",
		182: "Reduzierung",
		183: "Kupplungen (Verfahrenstechnik)",
		184: "Syphon",
		185: "Presse",
		186: "Vorkonfektioniert",
		187: "Anzeigegerät",
		188: "Meldeleuchte",
		189: "Messwertschreiber",
		190: "Meldeeirichtung, akustisch",
		191: "Fehlerspannungs-Schutzschalter",
		192: "Testverbinder (Klemmen, Stecker)",
		193: "Motorschutzschalter",
		194: "Schutzeinrichtung",
		195: "Sicherungsausautomat",
		196: "Meldeeinrichtung, akustisch (Fluid)",
		197: "Meldeeinrichtung, optisch",
		198: "Messwertschreiber (Fluid)",
		199: "Logikbauteil",
		200: "Artikel (Quelle)",
		201: "Allgemeine",
		202: "Ventil / Verteiler",
		203: "Schutzkreis",
		204: "Analoges Sensor",
		205: "Digitales Sensor, allgemein",
		206: "Endschalter",
		207: "Grenzwertgeber",
		208: "Lichtschranke",
		209: "Näheungsschalter",
		210: "Schalter / Taster",
		211: "Generator",
		212: "Artikel (Ziel)",
		213: "Spannungsquelle",
		214: "Sammelschienen-Abdeckung",
		215: "Schwenkrahmen",
		216: "Montage-Chassis",
		217: "Montageschiene",
		218: "Buchseneinsatz",
		219: "Rohre (Fluid)",
		220: "Schaltplatine (Klemmen, Stecker)",
		221: "Schaltbrücke (Klemmen, Stecker)",
		222: "Steckaufsatz (Klemmen, Stecker)",
		223: "Schlauche (Verfahrenstechnik)",
		224: "Rohe (Verfahrenstechnik)",
		225: "Kabel / Schlauchbefestigung",
		226: "Kabel / Schlauchschutz",
		227: "Kabel / Schlauchschutz",
		228: "Flachbandkabel",
		229: "Crimpkontakt",
		230: "Kontaktleinsatz",
		231: "Schütze",
		232: "Hilfsblock",
		233: "Hochdruckanlagen",
		234: "Hochdrucktanks",
		235: "Hydrauliktanks",
		236: "Klemme (Klemmen, Stecker)",
		237: "Kühlaggregate",
		238: "Schaltschrankkühlgeräte",
		239: "Schraubenpsindelkompressoren",
		240: "Scrollkompressoren",
		241: "Wärmetauscher",
		242: "Zentralschmieraggregate",
		243: "Anschlussplatten",
		244: "Adapterplatten",
		245: "Reduzierplatten",
		246: "Blockgehäuse",
		247: "Schienenanschlusplatten",
		248: "Reihenschlusplatten",
		249: "Steuerblöcke",
		250: "Zwischenplatten",
		251: "Hydromotoren",
		268: "Schwenkantrieb",
		269: "Zylinder",
		270: "Endwinkel (Klemmen, Stecker)",
		271: "Doppelumschaltfilter",
		272: "Druckluftfilter",
		273: "Grafitfilter",
		274: "Leitungstief",
		275: "Rückluftfilter",
		276: "Rückkupplung vollautomatisch",
		277: "Kupplungs-Motorpumpen",
		278: "Klemmenschild (Klemmen, Stecker)",
		279: "Schläuche (Fluid)",
		280: "Messkupplungen",
		281: "Verschlusskupplungen",
		282: "Schläuche (Fluid)",
		283: "Manometer",
		284: "Verschiedenes",
		285: "Thermometer",
		286: "Kompressoren",
		287: "Konstantpumpen",
		288: "Kreiselpumpen",
		289: "Pumpen",
		290: "Weiche Schilder (Klemmen, Stecker)",
		291: "Schraubenspindelpumpen",
		292: "Verstellpumpen",
		293: "Druckschalter",
		294: "Fehlerspannungs-Schutzschalter",
		295: "Signalaufnehmer-Manometer",
		296: "Näherungsschalter (Fluid)",
		297: "Störungsmelder",
		298: "Temperatursensoren",
		299: "Absperrspeicher",
		50:  "Kühlaggregate",
		51:  "Schaltschrankkühlgeräte",
		52:  "Schraubenpsindelkompressoren",
		53:  "Scrollkompressoren",
		54:  "Wärmetauscher",
		55:  "Zentralschmieraggregate",
		56:  "Anschlussplatten",
		57:  "Adapterplatten",
		58:  "Reduzierplatten",
		59:  "Blockgehäuse",
		60:  "Schienenanschlusplatten",
		61:  "Reihenschlusplatten",
		62:  "Steuerblöcke",
		63:  "Zwischenplatten",
		64:  "Hydromotoren",
		68:  "Schwenkantrieb",
		69:  "Zylinder",
		70:  "Endwinkel (Klemmen, Stecker)",
		71:  "Doppelumschaltfilter",
		72:  "Druckluftfilter",
		73:  "Grafitfilter",
		74:  "Leitungstief",
		75:  "Rückluftfilter",
		76:  "Rückkupplung vollautomatisch",
		77:  "Kupplungs-Motorpumpen",
		78:  "Klemmenschild (Klemmen, Stecker)",
		79:  "Schläuche (Fluid)",
		80:  "Messkupplungen",
		81:  "Verschlusskupplungen",
		82:  "Schläuche (Fluid)",
		83:  "Manometer",
		84:  "Verschiedenes",
		85:  "Thermometer",
		86:  "Kompressoren",
		87:  "Konstantpumpen",
		88:  "Kreiselpumpen",
		89:  "Pumpen",
		90:  "Weiche Schilder (Klemmen, Stecker)",
		91:  "Schraubenspindelpumpen",
		92:  "Verstellpumpen",
		93:  "Druckschalter",
		94:  "Fehlerspannungs-Schutzschalter",
		95:  "Signalaufnehmer-Manometer",
		96:  "Näherungsschalter (Fluid)",
		97:  "Störungsmelder",
		98:  "Temperatursensoren",
		99:  "Absperrspeicher",
	}
}
