// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlameStartup():Promise<boolean>;

export function Dailyvergleich():Promise<void>;

export function Dialog():Promise<string>;

export function ExcelChoice(arg1:string,arg2:string):Promise<void>;

export function ExcelChoice1(arg1:string,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ImportStueckliste(arg1:string,arg2:string):Promise<{[key: string]: Array<string>}|{[key: string]: Array<string>}>;

export function Lagerbestand(arg1:string):Promise<void>;

export function ListTrees():Promise<void>;

export function LoadCSV(arg1:string):Promise<void>;

export function Message(arg1:string):Promise<string>;

export function NewProject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StuecklisteSum(arg1:string):Promise<void>;

export function Test(arg1:string):Promise<string>;

export function VerbindungRead():Promise<void>;

export function XMLTest():Promise<void>;
