// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProdukt():Promise<void>;

export function BlameStartup():Promise<boolean>;

export function CurrentProject():Promise<void>;

export function Dialog():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Lagerbestand(arg1:string):Promise<void>;

export function ListTrees():Promise<void>;

export function LoadCSV(arg1:string):Promise<void>;

export function Message(arg1:string):Promise<string>;

export function NewProject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function NewProject2():Promise<void>;

export function Test(arg1:string):Promise<string>;
