// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProdukt() {
  return window['go']['main']['App']['AddProdukt']();
}

export function BlameStartup() {
  return window['go']['main']['App']['BlameStartup']();
}

export function CurrentProject() {
  return window['go']['main']['App']['CurrentProject']();
}

export function Dailyvergleich() {
  return window['go']['main']['App']['Dailyvergleich']();
}

export function Dialog() {
  return window['go']['main']['App']['Dialog']();
}

export function ExcelChoice(arg1, arg2) {
  return window['go']['main']['App']['ExcelChoice'](arg1, arg2);
}

export function ExcelChoice1(arg1, arg2) {
  return window['go']['main']['App']['ExcelChoice1'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportStueckliste(arg1, arg2) {
  return window['go']['main']['App']['ImportStueckliste'](arg1, arg2);
}

export function Jsonwrite() {
  return window['go']['main']['App']['Jsonwrite']();
}

export function Lagerbestand(arg1) {
  return window['go']['main']['App']['Lagerbestand'](arg1);
}

export function ListTrees() {
  return window['go']['main']['App']['ListTrees']();
}

export function LoadCSV(arg1) {
  return window['go']['main']['App']['LoadCSV'](arg1);
}

export function Message(arg1) {
  return window['go']['main']['App']['Message'](arg1);
}

export function NewProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewProject'](arg1, arg2, arg3);
}

export function NewProject2() {
  return window['go']['main']['App']['NewProject2']();
}

export function StuecklisteSum(arg1) {
  return window['go']['main']['App']['StuecklisteSum'](arg1);
}

export function StuecklisteSum2(arg1) {
  return window['go']['main']['App']['StuecklisteSum2'](arg1);
}

export function Test(arg1) {
  return window['go']['main']['App']['Test'](arg1);
}

export function VerbindungRead() {
  return window['go']['main']['App']['VerbindungRead']();
}

export function XMLTest() {
  return window['go']['main']['App']['XMLTest']();
}
