// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProdukt() {
  return window['go']['main']['App']['AddProdukt']();
}

export function BlameStartup() {
  return window['go']['main']['App']['BlameStartup']();
}

export function CurrentProject() {
  return window['go']['main']['App']['CurrentProject']();
}

export function ExportFile(arg1) {
  return window['go']['main']['App']['ExportFile'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportFile(arg1) {
  return window['go']['main']['App']['ImportFile'](arg1);
}

export function ListTrees() {
  return window['go']['main']['App']['ListTrees']();
}

export function LoadCSV(arg1) {
  return window['go']['main']['App']['LoadCSV'](arg1);
}

export function MessageDialog() {
  return window['go']['main']['App']['MessageDialog']();
}

export function NewProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewProject'](arg1, arg2, arg3);
}

export function NewProject2() {
  return window['go']['main']['App']['NewProject2']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenMultipleFilesDialog() {
  return window['go']['main']['App']['OpenMultipleFilesDialog']();
}

export function SaveFileDialog() {
  return window['go']['main']['App']['SaveFileDialog']();
}

export function Test(arg1) {
  return window['go']['main']['App']['Test'](arg1);
}
