// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dialog() {
  return window['go']['main']['App']['Dialog']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Message(arg1) {
  return window['go']['main']['App']['Message'](arg1);
}

export function Test(arg1) {
  return window['go']['main']['App']['Test'](arg1);
}
